"""mock adapter — deterministic stand-ins for the coding CLIs.

Used by `pipe run --mock` to exercise the full engine (edges, loops,
limits, events) offline. Produces a real, verifiable static site.
"""
from __future__ import annotations

import os

from .. import store
from .base import StageCtx, StageResult

_SITE = {
    "index.html": """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{task}</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <main>
    <h1>{task}</h1>
    <p>Generated by the mock implementer.</p>
    <button id="go">Click me</button>
  </main>
  <script src="script.js"></script>
</body>
</html>
""",
    "style.css": "body{font-family:system-ui;margin:3rem auto;max-width:42rem}\n",
    "script.js": "document.getElementById('go').onclick=()=>alert('hi')\n",
}


def run(ctx: StageCtx) -> StageResult:
    name = ctx.stage.name
    if name == "plan":
        ctx.artifacts_dir.mkdir(parents=True, exist_ok=True)
        plan = ctx.artifacts_dir / "plan.md"
        plan.write_text(
            f"# Plan\n\nBuild: {ctx.task}\n\n## Tasks\n"
            "- index.html — page structure\n- style.css — styles\n"
            "- script.js — interaction\n\n## Acceptance criteria\n"
            "- index.html parses; all local refs resolve; no TODO markers\n")
        store.sync_artifacts(ctx)
        return StageResult("done", output="mock plan written")
    if name == "implement":
        for fname, content in _SITE.items():
            text = content.replace("{task}", ctx.task)
            (ctx.workspace / fname).write_text(text)
        # test hook: PIPE_MOCK_FAIL_ONCE=1 ships a broken site on round 0
        if os.environ.get("PIPE_MOCK_FAIL_ONCE") and ctx.round == 0:
            (ctx.workspace / "index.html").write_text(
                "<html><body>TODO: finish</body><img src='missing.png'>")
        return StageResult("done", output="mock site written")
    if name == "review":
        return StageResult("approve", output="VERDICT: APPROVE")
    return StageResult("done", output=f"mock:{name}")
